name: CI integrations

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

defaults:
  run:
    shell: bash

jobs:

  pytest:
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-11, windows-2022]
        python-version: ['3.7', '3.10']
        requires: ['oldest', 'latest']
        exclude:
          - {python-version: '3.7', requires: 'latest'}
          - {python-version: '3.10', requires: 'oldest'}
          - {python-version: '3.10', os: 'windows'}  # todo: https://discuss.pytorch.org/t/numpy-is-not-available-error/146192
        include:
          - {python-version: '3.10', requires: 'latest', os: 'ubuntu-22.04'}
          - {python-version: '3.10', requires: 'latest', os: 'macOS-12'}
    env:
      PYTEST_ARTEFACT: test-results-${{ matrix.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}.xml
      PYTORCH_URL: https://download.pytorch.org/whl/cpu/torch_stable.html

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    # seems that MacOS jobs take much more than orger OS
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: ./.github/actions/caching
      with:
        os: ${{ runner.os }}
        # requires: ${{ matrix.requires }}
        python-version: ${{ matrix.python-version }}
        offset: "integrate"

    - name: Set min. dependencies
      if: inputs.requires == 'oldest'
      run: python .github/assistant.py set-oldest-versions --req_files=requirements/integrate.txt

    - name: Freeze PIL (hotfix)
      # import of PILLOW_VERSION which they recently removed in v9.0 in favor of __version__
      run: pip install "Pillow<9.0"  # It messes with torchvision

    - name: Install all dependencies
      run: |
        set -e
        pip install -r requirements/test.txt
        pip install -r requirements/integrate.txt --find-links $PYTORCH_URL --upgrade-strategy eager
        python ./requirements/adjust-versions.py requirements.txt
        python ./requirements/adjust-versions.py requirements/image.txt
        cat requirements.txt
        pip install -e . --find-links $PYTORCH_URL
        pip list

    - name: Integrations
      working-directory: ./tests
      env:
        PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
      run: python -m pytest integrations -v --durations=25
