name: CI testing - PyTorch & Conda

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

defaults:
  run:
    shell: bash -l {0}

jobs:
  check-diff:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/focus-diff.yml

  conda:
    runs-on: ubuntu-20.04
    needs: check-diff
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        pytorch-version: ["1.8", "1.9", "1.10", "1.11"]
        include:
          - {python-version: '3.10', pytorch-version: '1.12'}
          - {python-version: '3.10', pytorch-version: '1.13'}
    env:
      PYTEST_ARTEFACT: test-conda-py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}.xml

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 75
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/caching
      with:
        os: ${{ runner.os }}
        python-version: ${{ matrix.python-version }}
        offset: "pt"

    # https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf
    # https://gist.github.com/mwouts/9842452d020c08faf9e84a3bba38a66f
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        # miniconda-version: "4.7.12"
        python-version: ${{ matrix.python-version }}
        channels: pytorch,pytorch-test,pytorch-nightly,conda-forge
        channel-priority: true
        # auto-activate-base: true
        # environment-file: ./environment.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      # prevent hanging Conda creations
      timeout-minutes: 10

    - name: Update Environment
      run: |
        sudo apt install libsndfile1
        conda info
        conda install cpuonly mkl ffmpeg pytorch=${{ matrix.pytorch-version }} torchvision packaging
        conda list
        pip --version
        python ./requirements/adjust-versions.py requirements.txt
        pip install --requirement requirements/test.txt --quiet
        python ./.github/assistant.py prune-packages requirements/image.txt torchvision
        python ./.github/assistant.py prune-packages requirements/detection.txt torchvision
        # import of PILLOW_VERSION which they recently removed in v9.0 in favor of __version__
        pip install -q "Pillow<9.0"  # It messes with torchvision
        pip install -e . -r requirements/devel.txt "torch==${{ matrix.pytorch-version }}.*" -f $TORCH_URL
        pip list
        python -c "from torch import __version__ as ver; assert '.'.join(ver.split('.')[:2]) == '${{ matrix.pytorch-version }}', ver"
      env:
        TORCH_URL: https://download.pytorch.org/whl/cpu/torch_stable.html

    - name: DocTests
      working-directory: ./src
      # NOTE: run coverage on tests does not propagate failure status for Win, https://github.com/nedbat/coveragepy/issues/1003
      run: python -m pytest torchmetrics

    - uses: ./.github/actions/unittesting
      if: ${{ needs.check-diff.outputs.test-dirs != '' }}
      with:
        os: ${{ runner.os }}
        python-version: ${{ matrix.python-version }}
        pytorch-version: ${{ matrix.pytorch-version }}
        dirs: ${{ needs.check-diff.outputs.test-dirs }}
        test-timeout: "--timeout=120"
        shell-type: bash -l {0}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tests/coverage.xml
        flags: cpu,conda,unittests,${{ runner.os }},python${{ matrix.python-version }},torch${{ matrix.pytorch-version }}
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
